# fly.toml app configuration file generated for przyczepki-zary on 2023-11-25T15:42:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "przyczepki-zary"
primary_region = "waw"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
